apiVersion: v1
kind: Service
metadata:
  name: grok-exporter
  namespace: development
  labels:
    app: grok-service
spec:
  selector:
    app: haproxy-logging
  ports:
    - name: metrics
      port: 9144
      targetPort: 9144
      nodePort: 30001
  type: NodePort
