apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: development
  labels:
    app: haproxy-service
spec:
  type: NodePort
  selector:
    app: haproxy-logging
  ports:
    - name: haproxy
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: metrics
      port: 8404
      targetPort: 8404
      nodePort: 30081


# apiVersion: v1
# kind: Service
# metadata:
#   name: haproxy-service
#   namespace: development
# spec:
#   selector:
#     app: haproxy-logging
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP
