apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-logging
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-logging
  template:
    metadata:
      labels:
        app: haproxy-logging
    spec:
      containers:
        - name: haproxy
          image: mesivayenduri/haproxy-loggging:v8
          imagePullPolicy: Always
          ports:
            - name: haproxy
              containerPort: 80
            - name: metrics
              containerPort: 8404
          volumeMounts:
            - name: haproxy-logs
              mountPath: /app/haproxy
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1

        - name: grok-exporter
          image: mesivayenduri/grok_exporter:v1
          ports:
            - containerPort: 9144
              name: haproxy
          volumeMounts:
            - name: haproxy-logs
              mountPath: /app/haproxy
            - name: grok-exporter-config
              mountPath: /grok/config.yml
              subPath: config.yml
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1

        - name: logrotate
          image: mesivayenduri/logrotate:v1
          volumeMounts:
            - name: haproxy-logs
              mountPath: /app/haproxy
            - name: logrotate-config
              mountPath: /etc/logrotate.conf
              subPath: logrotate.conf
          resources:
            requests:
              memory: 512Mi
              cpu: "0.01"
            limits:
              memory: 512Mi
              cpu: "0.03"

      volumes:
        - name: haproxy-logs
          emptyDir: {}
        - name: grok-exporter-config
          configMap:
            name: grok-exporter-config
        - name: logrotate-config
          configMap:
            name: logrotate-config
